
// Mock data for animes
export const animes = [
  {
    id: "naruto",
    title: "Naruto",
    image: "https://m.media-amazon.com/images/M/MV5BZmQ5NGFiNWEtMmMyMC00MDdiLTg4YjktOGY5Yzc2MDUxMTE1XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    description: "Naruto Uzumaki, a mischievous adolescent ninja, struggles as he searches for recognition and dreams of becoming the Hokage, the village's leader and strongest ninja.",
    rating: 8.4,
    year: "2002",
    genre: ["Action", "Adventure", "Comedy", "Martial Arts", "Fantasy"],
  },
  {
    id: "one-piece",
    title: "One Piece",
    image: "https://m.media-amazon.com/images/M/MV5BODcwNWE3OTMtMDc3MS00NDFjLWE1OTAtNDU3NjgxODMxY2UyXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_.jpg",
    description: "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger. The famous mystery treasure named 'One Piece'.",
    rating: 8.9,
    year: "1999",
    genre: ["Action", "Adventure", "Comedy", "Fantasy", "Shounen"],
  },
  {
    id: "attack-on-titan",
    title: "Attack on Titan",
    image: "https://flxt.tmsimg.com/assets/p10701949_b_v8_ah.jpg",
    description: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    rating: 9.0,
    year: "2013",
    genre: ["Action", "Drama", "Fantasy", "Horror", "Thriller"],
  },
  {
    id: "demon-slayer",
    title: "Demon Slayer",
    image: "https://m.media-amazon.com/images/M/MV5BZjZjNzI5MDctY2Y4YS00NmM4LTljMmItZTFkOTExNGI3ODRhXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg",
    description: "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon slowly. Tanjiro sets out to become a demon slayer to avenge his family and cure his sister.",
    rating: 8.7,
    year: "2019",
    genre: ["Action", "Fantasy", "Adventure", "Supernatural", "Historical"],
  },
  {
    id: "jujutsu-kaisen",
    title: "Jujutsu Kaisen",
    image: "https://m.media-amazon.com/images/M/MV5BNzQyYzU3Y2MtOWY2Yy00ZGM2LTg3ZTUtMDJkZTJiMmEzMjYxXkEyXkFqcGdeQXVyMTI2NTY3NDg5._V1_.jpg",
    description: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    rating: 8.6,
    year: "2020",
    genre: ["Action", "Fantasy", "Horror", "Supernatural", "Shounen"],
  },
  {
    id: "my-hero-academia",
    title: "My Hero Academia",
    image: "https://m.media-amazon.com/images/M/MV5BOGZmYjdjN2UtNjAwZi00YmEyLWFhNTEtNjM1OTc5ODg0MGEyXkEyXkFqcGdeQXVyMTA1NjQyNjkw._V1_.jpg",
    description: "A superhero-loving boy without any powers is determined to enroll in a prestigious hero academy and learn what it really means to be a hero.",
    rating: 8.4,
    year: "2016",
    genre: ["Action", "Comedy", "Superhero", "School", "Shounen"],
  },
  {
    id: "fullmetal-alchemist-brotherhood",
    title: "Fullmetal Alchemist: Brotherhood",
    image: "https://m.media-amazon.com/images/M/MV5BZmEzN2YzOTItMDI5MS00MGU4LWI1NWQtOTg5ZThhNGQwYTEzXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    description: "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes wrong and leaves them in damaged physical forms.",
    rating: 9.1,
    year: "2009",
    genre: ["Action", "Adventure", "Drama", "Fantasy", "Magic"],
  },
  {
    id: "death-note",
    title: "Death Note",
    image: "https://m.media-amazon.com/images/M/MV5BNjRiNmNjMmMtN2U2Yi00ODgxLTk3OTMtMmI1MTI1NjYyZTEzXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_.jpg",
    description: "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
    rating: 9.0,
    year: "2006",
    genre: ["Mystery", "Psychological", "Supernatural", "Thriller", "Crime"],
  },
  {
    id: "hunter-x-hunter",
    title: "Hunter x Hunter",
    image: "https://m.media-amazon.com/images/M/MV5BZjNmZDhkN2QtNDYyZC00YzJmLTg0ODUtN2FjNjhhMzE3ZmUxXkEyXkFqcGdeQXVyNjc2NjA5MTU@._V1_FMjpg_UX1000_.jpg",
    description: "Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends and his potential, he seeks for his father who left him when he was younger.",
    rating: 8.9,
    year: "2011",
    genre: ["Action", "Adventure", "Fantasy", "Martial Arts", "Shounen"],
  },
  {
    id: "tokyo-revengers",
    title: "Tokyo Revengers",
    image: "https://m.media-amazon.com/images/M/MV5BMzJiYzdjNjQtZWVkOS00YTY2LWE0ZTQtNTFiNGRhY2NiYzUyXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    description: "Takemichi Hanagaki learns that his ex-girlfriend was killed by the Tokyo Manji Gang. When he's almost killed himself, he travels 12 years into the past to try to save her.",
    rating: 8.1,
    year: "2021",
    genre: ["Action", "Drama", "Supernatural", "School", "Delinquents"],
  },
  {
    id: "bleach",
    title: "Bleach",
    image: "https://m.media-amazon.com/images/M/MV5BZjE0YjVjODQtZGY2NS00MDcyLThhMDAtZGQwMTZiOWNmNjRiXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_FMjpg_UX1000_.jpg",
    description: "High school student Ichigo Kurosaki, who has the ability to see ghosts, gains soul reaper powers from Rukia Kuchiki and sets out to save the world from Hollows.",
    rating: 8.1,
    year: "2004",
    genre: ["Action", "Adventure", "Comedy", "Supernatural", "Shounen"],
  },
  {
    id: "doraemon",
    title: "Doraemon",
    image: "https://m.media-amazon.com/images/M/MV5BNTg0NmI1ZGQtZTUxNC00NTgxLWEzZjctZWRmNzBmNzYzNzgyXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg",
    description: "Doraemon is a cat-like robot who appears in the present to steer Nobita, a dumb, naive and clumsy boy, on the right path in order to secure his future.",
    rating: 8.2,
    year: "1979",
    genre: ["Comedy", "Kids", "Sci-Fi", "Slice of Life", "School"],
  },
  {
    id: "shinchan",
    title: "Crayon Shin-chan",
    image: "https://m.media-amazon.com/images/M/MV5BMTgyYjQyZGMtYWI3Yy00N2VhLThhMzktOWYxYjEwM2MzYWQ0XkEyXkFqcGdeQXVyNjk1Njg5NTA@._V1_.jpg",
    description: "The misadventures of a kindergartner named Shin Nohara and his parents, neighbors, and friends.",
    rating: 7.7,
    year: "1992",
    genre: ["Comedy", "Slice of Life", "Kids", "School", "Family"],
  },
  {
    id: "lookism",
    title: "Lookism",
    image: "https://m.media-amazon.com/images/M/MV5BOWQwZDU5NzktYjhiYS00NGNkLTg1N2EtYzNjNGNmN2RkMDBhXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_.jpg",
    description: "A high school student who after being bullied for his looks, wakes up one day to discover he has two bodies - one that is conventionally handsome, and one that is his original appearance.",
    rating: 8.0,
    year: "2022",
    genre: ["Action", "Drama", "School", "Psychological", "Martial Arts"],
  },
  {
    id: "your-name",
    title: "Your Name",
    image: "https://m.media-amazon.com/images/M/MV5BNGYyNmI3M2YtNzYzZS00OTViLTkxYjAtZDIyZmE1NTUyMzc2XkEyXkFqcGdeQXVyMTA4NjE0NjEy._V1_.jpg",
    description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    rating: 8.8,
    year: "2016",
    genre: ["Romance", "Supernatural", "Drama", "School", "Slice of Life"],
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    image: "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_.jpg",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, and where humans are changed into beasts.",
    rating: 8.6,
    year: "2001",
    genre: ["Adventure", "Fantasy", "Family", "Mystery", "Supernatural"],
  },
  {
    id: "cowboy-bebop",
    title: "Cowboy Bebop",
    image: "https://m.media-amazon.com/images/M/MV5BZmQzMDE5ZWQtOTU1ZC00ZTE0LThiZWItNWMxNzkxMGE4NWRkXkEyXkFqcGdeQXVyNjc3MjQzNTI@._V1_.jpg",
    description: "The futuristic misadventures and tragedies of an easygoing bounty hunter and his partners.",
    rating: 8.9,
    year: "1998",
    genre: ["Action", "Adventure", "Drama", "Sci-Fi", "Space"],
  },
  {
    id: "spy-x-family",
    title: "Spy x Family",
    image: "https://m.media-amazon.com/images/M/MV5BNGY5MWFlMzYtMzg1ZS00YTVjLTk0NGUtMzQxNDY2ZmMwZDFkXkEyXkFqcGdeQXVyMTMzNDExODE5._V1_.jpg",
    description: "A spy on an undercover mission gets married and adopts a child as part of his cover. His wife and daughter have secrets of their own, and all three must strive to keep together.",
    rating: 8.5,
    year: "2022",
    genre: ["Action", "Comedy", "Slice of Life", "Supernatural", "Family"],
  },
  {
    id: "the-promised-neverland",
    title: "The Promised Neverland",
    image: "https://m.media-amazon.com/images/M/MV5BMTYwYjYyZDgtMTQ3My00YTI4LThmZTUtZmU1MjllOWRlOTdhXkEyXkFqcGdeQXVyMzgxODM4NjM@._V1_.jpg",
    description: "A group of the smartest kids at a seemingly perfect orphanage uncover its dark secret, and set in motion a dangerous and desperate escape plan.",
    rating: 8.4,
    year: "2019",
    genre: ["Horror", "Sci-Fi", "Mystery", "Psychological", "Thriller"],
  },
  {
    id: "dragon-ball-z",
    title: "Dragon Ball Z",
    image: "https://m.media-amazon.com/images/M/MV5BNGM5MTEyZDItZWNhOS00NzNkLTgwZTAtNWIzY2IzZmExOWMxXkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_.jpg",
    description: "After learning that he is from another planet, a warrior named Goku and his friends are prompted to defend it from an onslaught of extraterrestrial enemies.",
    rating: 8.7,
    year: "1989",
    genre: ["Action", "Adventure", "Fantasy", "Martial Arts", "Shounen"],
  },
  {
    id: "fruits-basket",
    title: "Fruits Basket",
    image: "https://m.media-amazon.com/images/M/MV5BNzI3OWYyNjgtMjQzZC00ZjlkLWIzZjItNWEyNjY4MjMxYmNiXkEyXkFqcGdeQXVyMTQ3MjMyMTYz._V1_.jpg",
    description: "After Tohru is taken in by the Soma family, she learns that twelve family members transform involuntarily into animals of the Chinese zodiac and helps them deal with the emotional pain caused by the transformations.",
    rating: 8.6,
    year: "2019",
    genre: ["Drama", "Romance", "Supernatural", "Comedy", "Slice of Life"],
  }
];
